### PR TITLE
Check if output filename was passed to the CLI - fixes #11

### LINKED ISSUE #11: Empty string as --output parameter creates the SVG file named 'true'
To reproduce run: 
`sqip ./input.png -o`

In the end it will create a file called `true` on the same directory where the command run.

### PR DESCRIPTION
**Pull request by alexnoz**
This PR is a fix for #11. It seems like the issue is caused by a bug in the `argv` library that interprets the presence of the `-o` option as `true` and then converts it to a string. Here we check if a user has actually passed any value to the option and if so, write the output to the file. If the value (or the option itself) is absent, write the output to `stdout`.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -81,6 +81,12 @@ const getInputfilePath = (targets, shouldThrow = false) => {
     return path.resolve(process.env.PWD, targets[0]);
 }
 
+// Sanity check: make sure that the value was passed to the `output` option
+// Fixes https://github.com/technopagan/sqip/issues/11
+const getOutputFilePath = () => {
+  const index = process.argv.findIndex(arg => arg == '-o' || arg == '--output');
```
Comment (efegurkan) [inline src/index.js]: I would personally prefer using strict equality check `===` and stick with a solution that uses `argv` still.

Comment (alexnoz) [reply src/index.js]: Would you like me try a different approach or only change equality checks? As I understand, we cannot determine if a user specified `true` as a output filename or passed `-o` option without any value if we use [options.output](https://github.com/technopagan/sqip/blob/master/src/index.js#L156) property for it.

Comment (efegurkan) [reply src/index.js]: >  As I understand, we cannot determine if a user specified true as a output filename or passed -o option without any value if we use options.output property for it.

That is true, actually `argv` parses the options correctly since something like `command -o` would be interpreted as `o=true`. But it does not check the value and converts the boolean value to path.

At some point we need to change `argv` with something else that would be the best solution. But for now going with your approach should work. 

@technopagan usually prefers warning/error if something is wrong. If he is also fine with the solution changing equality checks would be enough. 😄 

Cheers,

**Comment by alexnoz** [comment]
I've updated the PR. If you want to change `argv` to something else, take a look at [yargs](https://github.com/yargs/yargs) library, maybe you'll like it, it's awesome for this kind of things :+1:

**Comment by technopagan** [comment]
@alexnoz This is amazing work! Thank you so much for your help with SQIP! And thanks, @efegurkan, for reviewing it! 🤗
